version: '3.1'

services:

  frenchy:
    build: ./
    image: french-amortization:0.0.5
    ports:
      - 8000:8000
    environment:
      - DEBUG = ''
      - ALLOWED_HOSTS = ''
      - CSRF_TRUSTED_ORIGINS = ''
