# Generated by Django 4.2.4 on 2023-08-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitalization', models.FloatField()),
                ('interest', models.FloatField()),
                ('periods', models.IntegerField()),
            ],
        ),
    ]
